version: "2"

services:
  redis:
    container_name: atipwc-redis
    image: redis:5.0.7
    ports:
      - "6379:6379"
    networks:
      - atipwc-network

  first_app:
    build:
      context: .
      dockerfile: atipwc.dockerfile
    container_name: atipwc-first-app
    volumes:
      - ./:/code
    command: >
        bash -c "python first_app.py"
    networks:
      - atipwc-network

  celery-beer:
    build:
      context: .
      dockerfile: atipwc.dockerfile
    container_name: atipwc-celery-beer
    volumes:
      - ./:/code
    restart: unless-stopped
    command: celery -A celery_stuff.tasks worker -l debug -Q beer
    depends_on:
      - redis
      - first_app
    networks:
      - atipwc-network

  celery-coffee:
    build:
      context: .
      dockerfile: atipwc.dockerfile
    container_name: atipwc-celery-coffee
    volumes:
      - ./:/code
    restart: unless-stopped
    command: celery -A celery_stuff.tasks worker -l debug -Q coffee
    depends_on:
      - redis
      - first_app
    networks:
      - atipwc-network

networks:
  atipwc-network:
    driver: bridge
